Lambda-School-Labs/labs9-family-tabs

- MichaelBoegner.md
> Added ChildHome.js file for Child Home feature

- familytabs/package.json
- familytabs/src/App.js
- familytabs/src/Components/ParentHome.js
- familytabs/src/index.js
- familytabs/yarn.lock
Added React Router and React Router Dom dependencies. Added basic class component to parenthome.js. Routed parenthome component into app.js. Displaying on app. 
> added basic homepage class component, and routed into app.js

- netlify.toml
> netlify_ryan

- familytabs/package.json
- familytabs/public/index.html
- familytabs/src/App.js
- familytabs/src/Components/LandingPage.js
- familytabs/yarn.lock
> Created unstyled landing page for user arrival

- familytabs/public/index.html
- familytabs/src/App.js
- familytabs/src/Components/LandingPage.js
- familytabs/src/Components/Navigation.css
- familytabs/src/Components/ParentHome.js
- familytabs/src/index.css
Cleaned up file structure, myers reset, box-sizing border-box, link from landing page to parent home, nav bar independent from landing page.
> Cleaned up file structure, myers reset, box-sizing border-box, link from landing page to parenthome, nav bar independent from landing page

- server/server.js
Started a post endpoint. Added required fields for create event form including event location and
user information.
> started post endpoint, and added required fields for create event form

- server/server.js
Added time and date to required fields in post endpoint for create event form. 
> updated post endpoint to include time and date fields as required to submit event

- server/server.js
> Post Endpoint Further Defined

- server/server.js
Added endpoint /familymembers/:id which gathers all of the data for each family member. Returns `err: 'no family at that id' ` when db call returns empty array. 
> call family members by family id endpoint

- database/migrations/20190109154349_event-with-users.js
- familytabs/src/Components/Checkout.js
- familytabs/src/Components/LandingPage.js
- familytabs/src/stripe.js
- package.json
- yarn.lock
added front end stripe code and pushing for sania to add token gen
> added front end stripe code and pushing for sania to add token gen

- CodePieces.md
algorithm to reduce data to users stacked by event in CodePieces.md
> algorithm to reduce data to users stacked by event in CodePieces.md

- familytabs/.env
- familytabs/package.json
- familytabs/src/Components/Callback.js
- familytabs/src/auth/Auth.js
- familytabs/src/auth/AuthContext.js
- familytabs/src/auth/PrivateRoute.js
- familytabs/src/auth/PrivateRoutes.js
- familytabs/src/auth/PublicRoute.js
- familytabs/yarn.lock
- netlify.toml
Auth context created. Public private routes created. Not implemented. Tried to avoid merge conflict. 
> Auth0frontend ryan

- familytabs/.env
- familytabs/src/App.js
- familytabs/src/index.js
> fixes broken route for auth0 configuration

- familytabs/.env
Merge conflict resulted in re-added stripe config to env file
> Re-added stripe env config

- familytabs/src/Server/Constants/frontend.js
- familytabs/src/Server/Constants/server.js
- familytabs/src/Server/index.js
- familytabs/src/Server/server.js
Finished code for functionality on stripe for back-end. 
> Finished Stripe Server to Functionality on Backend

- familytabs/src/Server/Constants/frontend.js
- familytabs/src/Server/server.js
uncommented original whitelist and corsoptions code and commented out other corsoptions leaving it for reference. Changed frontend to point to 3000 instead of 8080 in the frontend.js. Payment processed
> uncommented original whitelist and corsoptions code and commented out . . .

- familytabs/src/Components/Household.js
Household ready to display data by family. 
> Household Ready to Display Data

- familytabs/src/Components/Household.js
Added map statement for family data to render on front end application.
> added map statement for family data

- familytabs/src/Components/Household.js
> typo fix for info rendering on screen

- familytabs/src/App.js
- familytabs/src/Components/Navigation.js
- familytabs/src/index.css
Added and Changed several fonts for pages and nav. 
> Added and Changed Fonts for Nav

- familytabs/src/Components/Household.js
Trying to fix heroku error for household tab not rendering family data. 
> still trying to fix heroku error

- familytabs/src/Components/Calendar.js
Changes made to font, text alignment, and padding for the calendar.  Removal of colors to introduce a clean look added. 
> Changes made to calendar styling

- familytabs/src/App.js
- familytabs/src/Components/Calendar.js
- familytabs/src/Components/Household.js
Modified calendar size to be larger approaching size of desktop screen
> Modified calendar size to be larger approaching size of desktop screen

- familytabs/src/App.js
- familytabs/src/Components/Calendar.js
Added 20px padding-left for app css
> Added 20px padding-left for app css

- README.md
Completed skeleton formatting and began adding contents for readme. 
> Created Skeleton Formatting and Began Contents for Readme File.

- familytabs/src/Components/Navigation.js
- familytabs/src/Components/VerifyProfile.js
- familytabs/src/context/FamilyContext.js
- server/server.js
- server/stateCalls.js
fixed state server calls. Still working on storing that data to state. Work in progress had a wide footprint and fixed some broken functionality so I wanted to make sure it was up
> fixed state server calls.

- familytabs/src/Components/Billing.js
- familytabs/src/Components/BillingCard.js
- familytabs/src/Components/LandingPage.js
Billing component added with initial card and styling. 
> Initial Billing Card and Styling Added

- familytabs/src/Components/BillingCard.js
> billing page complete for now - needs further styling

- familytabs/src/Components/VerifyProfile.js
- familytabs/src/context/FamilyContext.js
- server/stateCalls.js
Now when any user logs in, all the family, event for family, and profile information is loaded and stored to state. Will persist on reload as long as token is valid.
> all data loaded to state on login.

- familytabs/package.json
- familytabs/src/App.js
- familytabs/src/Components/InfoCarousel.js
- familytabs/src/Components/LandingPage.js
- familytabs/src/Components/slider.css
- familytabs/yarn.lock
Added carousel to landing page. 
> added carousel to landing page

- server/scheduler.js
- server/server.js
Cron works with new organized endpoints now
> cron connected to changed endpoints in own file now

- familytabs/src/Components/Settings.js
Added a form for updating account information on settings page. 
> added form to account page

- familytabs/src/App.js
- familytabs/src/Components/LandingPage.js
- familytabs/src/Components/SignUp.js
Added sign up page where new user can select option for account. 
> Added a sign up page that new user can click to decide option

- familytabs/src/Components/NotificationTabs.js
Media queries began on notification page. 
> Began Initial Media Query Set-up

- familytabs/src/Components/NotificationCard.js
- familytabs/src/Components/Notifications.js
Event showing under pending tab on notifications page. 
> event showing under pending tab in notifications

- familytabs/src/Components/Navigation.js
Previous stylings integrated in current nav bar, some additional styling needed for hamburger adjustment. 
> Restored original styling, but within collapsable Nav

- familytabs/src/Components/NotificationCard.js
- familytabs/src/Components/Notifications.js
Added Approve/Decline buttons, link to calendar, and axios put code for onClick 
> added buttons, link, and some axios code for onClick for notification buttons. 

- familytabs/src/App.js
- familytabs/src/Components/Navigation.js
Added styling to make navburger more responsive with page content. 
> Made Nav Bar more Responsive

- familytabs/package.json
- familytabs/src/Components/AddEvent.js
- familytabs/src/Components/Calendar.js
- familytabs/src/Components/CreatableAdvanced.js
- familytabs/yarn.lock
- server/server.js
Calendar modal now creates locations and event types.
> location eventtypes from calendar

- familytabs/src/App.js
- familytabs/src/Components/ParentHome.js
Margin added on app, and logout button on family tabs. 
> added margin and logout button

- familytabs/src/Components/calendar/AddEvent.js
- familytabs/src/Components/calendar/Calendar.js
- server/stateCalls.js
Calendar component now has a filter by family member field. Default is unfiltered. New events appear in calendar instantly and no longer require reload.
> filter calendar by person. new events hotload into calendar

- familytabs/package.json
- familytabs/public/index.html
- familytabs/src/App.js
- familytabs/src/Components/LandingPage.js
- familytabs/yarn.lock
Added further styling to landing page, and added blueprint framework that we will be using going forward.
> further styling of landing page, and added bluprint framework

- familytabs/src/Components/VerifyProfile.js
- familytabs/src/Components/calendar/AddEvent.js
- familytabs/src/Components/calendar/Calendar.js
- familytabs/src/Components/calendar/ParentHome.js
- familytabs/src/Components/household/Household.js
- familytabs/src/Components/household/HouseholdModal.js
- server/routeMaker.js
- server/server.js
> create family modal

- familytabs/src/App.js
- familytabs/src/Components/LandingPage.js
Added further button styling, and landing page styling.
> further styling of landing page, needs text section

- familytabs/src/App.js
- familytabs/src/Components/Billing.js
- familytabs/src/Components/ButtonStyles.js
- familytabs/src/Components/LandingPage.js
Added a Button Component in order to be passed in on all pages. 
> Added a Button Component

- familytabs/src/Components/LandingPage.js
Styled landing page. Need to add photos and watermark logo. 
> Landingstyling sania

- familytabs/src/Components/calendar/Calendar.js
- familytabs/src/Components/household/Household.js
- familytabs/src/Components/household/HouseholdFamily.js
- familytabs/src/Components/household/HouseholdModal.js
Admin can edit family member information.
> admin can edit family

- familytabs/src/Components/LandingPage.js
Button styling, including hover and colors.
> added hover functions, button styling, and colors

- familytabs/src/Components/Navigation.js
Navbar refactored for stylistic reasons.  Logo interactive.  
> Refactored Navbar to include hover and styling changes

- familytabs/src/Components/calendar/Calendar.js
pending events are ochre, declinded events are red, active events are the light blue accent color of the logo
- [ x] I have added tests that prove my fix is effective or that my feature works
- [x ] New and existing unit tests pass locally with my changes
- [x ] There are no merge conflicts
> pending events are ochre declinded events are red

- familytabs/src/Components/VerifyProfile.js
- familytabs/src/Components/calendar/AddEvent.js
First login state load error fix. Profile data was loading nested off of first login. I thought I had fixed this, but I must have reverted it at some point.
> state bug fix

- familytabs/src/Components/Billing.js
- familytabs/src/Components/BillingCard.js
- familytabs/src/Components/NavBurger.js
- familytabs/src/Components/Navigation.js
Billing Styles added, code cleaned up on billing and nav page, added alternate colors to nav bar. 
> Styled Billing Page and Cleaned Up Some Code

- familytabs/src/Components/notifications/Notifications.js
modified tab borders to give more tab feel
> modified tab borders to give more tab feel

- familytabs/src/Components/notifications/EventCard.js
- familytabs/src/Components/notifications/Notifications.js
> pending events get buttons

- familytabs/src/Components/BillingCard.js
Adjusted Billing Styling, line height, and card box margins.
> Adjusted Billing Styling, line height, and card box margins.

- familytabs/src/Components/Settings.js
Some styling for form on settings page
> settings page styling

- familytabs/src/Components/Navigation.js
ballanced Logout padding, added underlines, all caps
> ballanced Logout padding, added underlines, all caps

- familytabs/package.json
- familytabs/src/Components/household/Household.js
- familytabs/src/Components/household/HouseholdFamily.js
- familytabs/src/Components/household/HouseholdModal.js
- familytabs/yarn.lock
- server/stateCalls.js
Notification settings moved to household component. React switch added for true/false edits.
> household controls admin settings

- familytabs/src/Components/household/Household.js
> slider switch functionality

- familytabs/src/Components/Billing.js
> billing page styling

- familytabs/src/Components/household/Household.js
- familytabs/src/Components/household/HouseholdFamily.js
Styled cards for household page
> household page card styling

- familytabs/src/Components/calendar/Calendar.js
> calendar responsive

- familytabs/src/Components/notifications/EventCard.js
- familytabs/src/Components/notifications/Notifications.js
> notification page styled and mostly responsive

- familytabs/src/Components/SignUp.js
Start Up page styled with components.
> Getting Start Page Styled

- familytabs/src/Components/calendar/AddEvent.js
- familytabs/src/Components/calendar/Calendar.js
- familytabs/src/Components/calendar/CreatableAdvanced.js
- familytabs/src/Components/household/HouseholdModal.js
- familytabs/src/Components/styled/components.js
- familytabs/src/auth/Auth.js
- server/server.js
> modal styling. created loc/eventtypes fill in

- README.md
Added four front-end dependences to Readme. 
> Added several dependencies to Readme.

- README.md
Further added to read me document. 
> Further added to read me

- README.md
Read me information for endpoints located in statecalls.js.
> Read me information for endpoints located in statecalls.js

- README.md
Added Routemaker and Running Scripts to Readme.
> Added Routemaker and Running Scripts to Readme

- server/stateCalls.js
> is scubscribed now in profile on state

- familytabs/src/Components/LandingPage.js
Adjusted landing page for new larger logo
> adjusted landing page for new larger logo

- familytabs/src/Components/VerifyProfile.js
Font color change for loading on verify page
> font color change for loading on verify page

- familytabs/src/Components/notifications/Notifications.js
Notification page updated with new styling.  Message added if no events are to be approved or denied. 
> Notification Page Updated

- familytabs/src/Components/Billing.js
- familytabs/src/Components/LandingPage.js
- familytabs/src/Components/calendar/Calendar.js
- familytabs/src/Components/household/Household.js
- familytabs/src/Components/notifications/Notifications.js
> Header styling consistency

- familytabs/src/Components/calendar/AlertModal.js
> Added Alert Modal Component

- familytabs/src/Components/calendar/Calendar.js
Agenda no longer displays dysfunctional header.  Clean display styled. 
> Fixed Agenda Styling on Calendar

- __tests__/index.js
- __tests__/stateCalls.js
- jest.config.js
- package.json
- server/stateCalls.js
- yarn.lock
> added supertest to check state call endpoints

- familytabs/package.json
- familytabs/src/Components/calendar/AddEvent.js
- familytabs/yarn.lock
- package.json
- yarn.lock
Fixed jest compatibility issues. If you are getting any errors in yarn starting your react script, just wipe your node modules and re install them
> fixed compatibility issues

- familytabs/src/Components/BillingCard.js
Changed styling of billing page.
> styling for billing page

- familytabs/src/Components/Billing.js
- familytabs/src/Components/BillingCard.js
- familytabs/src/Components/Checkout.js
- familytabs/src/Components/styled/components.js
> stripe purchase loads premium display

- familytabs/src/App.js
- familytabs/src/Components/Header.js
- familytabs/src/Components/VerifyProfile.js
- familytabs/src/Components/styled/components.js
> verify page beautyful
